version: "2.2"

services:
  mysql:
    image: mysql:8.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=lgg