name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # 소스코드 체크아웃
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build

      - name: Docker image Build
        run: docker build -t ghcr.io/ber01/lo-gak-gye:latest .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ber01
          password: ${{ secrets.CR_TOKEN }}

      - name: Docker image Push
        run: docker push ghcr.io/ber01/lo-gak-gye:latest

      - name: Get Public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-northeast-2'

      - name: Add GitHub Actions IP
        run: aws ec2 authorize-security-group-ingress \
                  --group-id ${{ secrets.SECURITY_GROUP_ID }} \
                  --protocol tcp \
                  --port 22 \
                  --cidr ${{ steps.ip.outputs.ipv4 }}/32

# 3번, 인바운드 관련 이슈가 해결되지 않아 실행이 불가능하다.
#      - name: Connect to EC2
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.EC2_SSH_HOST_NAME }}
#          username: ${{ secrets.EC2_SSH_USER }}
#          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
#          script: |
#            whoami
#            docker ps -a
